"""Visualization module."""

from libs.visualization.plots import (
    plot_accuracy_bars,
    plot_dashboard,
    plot_posterior_1d,
    plot_posterior_heatmap_network_nonnetwork,
    plot_posterior_histogram,
    plot_posterior_vs_signal,
    plot_prior,
    plot_reference_breakdown_aggregate,
    plot_reference_breakdown_score,
    plot_reference_breakdown_single_letter,
    plot_reference_breakdown_trust,
    plot_reference_signal_breakdown,
    plot_reference_signal_breakdown_aggregate,
    plot_reference_signal_breakdown_score,
    plot_reference_signal_breakdown_single_letter,
    plot_reference_signal_breakdown_trust,
    plot_reference_weighted_breakdown,
    plot_signal_distributions,
    reset_style,
    set_paper_style,
)

__all__ = [
    "set_paper_style",
    "reset_style",
    "plot_reference_weighted_breakdown",
    "plot_reference_breakdown_trust",
    "plot_reference_breakdown_score",
    "plot_reference_breakdown_single_letter",
    "plot_reference_breakdown_aggregate",
    "plot_reference_signal_breakdown",
    "plot_reference_signal_breakdown_trust",
    "plot_reference_signal_breakdown_score",
    "plot_reference_signal_breakdown_single_letter",
    "plot_reference_signal_breakdown_aggregate",
    "plot_signal_distributions",
    "plot_posterior_histogram",
    "plot_posterior_1d",
    "plot_posterior_vs_signal",
    "plot_prior",
    "plot_posterior_heatmap_network_nonnetwork",
    "plot_accuracy_bars",
    "plot_dashboard",
]
